# Generated by Django 6.0.6 on 2026-07-04 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('short_code', models.CharField(blank=True, max_length=20)),
                ('project_type', models.CharField(choices=[('TV Serial', 'TV Serial'), ('Movie', 'Movie'), ('Advertisement', 'Advertisement'), ('Web Series', 'Web Series'), ('Corporate', 'Corporate'), ('Event', 'Event'), ('Other', 'Other')], max_length=30)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Active', max_length=20)),
                ('billing_contact', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customers.customer')),
            ],
        ),
    ]
