# Generated by Django 6.0.6 on 2026-07-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Light', 'Light'), ('Grip', 'Grip'), ('Power', 'Power'), ('Generator', 'Generator'), ('Accessory', 'Accessory'), ('Other', 'Other')], max_length=30)),
                ('unit', models.CharField(choices=[('Nos', 'Nos'), ('Set', 'Set'), ('Pair', 'Pair'), ('Roll', 'Roll')], default='Nos', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
