# Generated by Django 6.0.6 on 2026-07-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='sac_code',
            field=models.CharField(default='998314', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='standard_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
