# Generated by Django 6.0.6 on 2026-07-07 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_equipment_sac_code_equipment_standard_rate'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiated_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_rates', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'equipment')},
            },
        ),
    ]
